server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.0.26:8761/eureka/
spring:
#  profiles: cloud
  application:
    name: config_service
  cloud:
    config:
#      label: master
      server:
        git:
          uri: https://github.com/gao2691714/config-repo
          basedir: /IdeaProjects/springCloudDemo/config_service_demo/basedir
#          username: gao2691714
#          password: gao2473666
